### ISSUE TITLE
HBaseClient fails to properly start.

### ISSUE THREAD

**Issue by nicktelford** [MeltwaterArchive/dropwizard-extra#2]
`HBaseClient` fails to properly start. 

Reported by Chaitanya Sharma.

```
INFO  [2012-11-18 22:05:25,924] org.apache.zookeeper.ZooKeeper: Initiating client connection, connectString=zoo1.dev,zoo2.dev,zoo3..dev sessionTimeout=5000 watcher=org.hbase.async.HBaseClient$ZKClient@28b47e5b
INFO  [2012-11-18 22:05:25,925] org.apache.zookeeper.ClientCnxn: Opening socket connection to server zoo2.dev/54.243.38.126:2181
INFO  [2012-11-18 22:05:25,925] org.hbase.async.HBaseClient: Need to find the -ROOT- region
INFO  [2012-11-18 22:05:25,929] org.apache.zookeeper.ClientCnxn: Socket connection established to zoo2.dev/54.243.38.126:2181, initiating session
INFO  [2012-11-18 22:05:25,991] org.apache.zookeeper.ClientCnxn: Session establishment complete on server zoo2.dev/54.243.38.126:2181, sessionid = 0x13abc039d76f58f, negotiated timeout = 5000
INFO  [2012-11-18 22:05:25,997] org.hbase.async.HBaseClient: Connecting to -ROOT- region @ 10.60.53.162:60020
WARN  [2012-11-18 22:05:25,998] org.hbase.async.HBaseClient: Couldn't connect to the RegionServer @ 10.60.53.162:60020
WARN  [2012-11-18 22:05:26,010] org.hbase.async.RegionClient: RPC rejected by the executor, ignore this if we're shutting down
! java.util.concurrent.RejectedExecutionException: Task org.jboss.netty.util.internal.DeadLockProofWorker$1@fcc06e0 rejected from java.util.concurrent.ThreadPoolExecutor@1bd7643a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3]
! at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2013)
! at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:816)
! at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1337)
! at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.register(NioClientSocketPipelineSink.java:219)
! at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:161)
! at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:111)
! at org.hbase.async.HBaseClient$RegionClientPipeline.sendDownstream(HBaseClient.java:2420)
! at org.jboss.netty.channel.Channels.connect(Channels.java:642)
! at org.jboss.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
! at org.hbase.async.HBaseClient.newClient(HBaseClient.java:2371)
! at org.hbase.async.HBaseClient.access$2600(HBaseClient.java:176)
! at org.hbase.async.HBaseClient$ZKClient$2.processResult(HBaseClient.java:2943)
! at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:570)
! at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:507)
```

asynchbase version: 1.4.0
Dropwizard version: 0.6.0-SNAPSHOT?

**Comment by SergeyMakarenko** [comment]
Do you have several instances of org.hbase.async.HBaseClient  in you application?
I had several async hbase clients in my test code. Also on each test completion I was shutting down unnecessary instances of async hbase and as a result the whole application freezes with this exception in logs.
If I do not shutdown those multiple instances of async hbase client then my tests were able to succeed.
